spring:
  main:
    log-startup-info: false
  shell:
    theme:
      name: enhanced
    command:
      history:
        enabled: false
      script:
        enabled: false
      version:
        show-build-group: true
        show-build-time: true
        show-build-artifact: true